# Compile options
DEBUG                       :=  1
SHOW_WARNING                :=  0

# Compile applications
APP                         :=  trt-infer
## You can also choose otherapplications. Currently, we support following applications:
## 1. trt-cuda
## 2. trt-infer
## 3. trt-tracker

# 根据当前的环境修改gcc和cuda的版本
CXX                         :=  g++
CUDA_VER                    :=  11.6

# opencv和TensorRT的安装目录
OPENCV_INSTALL_DIR          :=  /usr/local/include/opencv4
TENSORRT_INSTALL_DIR        :=  /home/zhongqi/packages/TensorRT

# 大家根据自己的机器的型号选择一下ARCH，这个是nvcc需要用到的参数
# GeForce RTX 3070, 3080, 3090cd 
ARCH= -gencode arch=compute_86,code=[sm_86,compute_86]
